"""empty message

Revision ID: 50ab074bec9a
Revises: 55e910a74826
Create Date: 2018-11-20 08:45:29.671788

"""

# revision identifiers, used by Alembic.
revision = '50ab074bec9a'
down_revision = '55e910a74826'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dbs', 'allow_csv_upload',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('slices_table_id_fkey', 'slices', type_='foreignkey')
    op.drop_constraint('slices_druid_datasource_id_fkey', 'slices', type_='foreignkey')
    op.drop_column('slices', 'table_id')
    op.drop_column('slices', 'druid_datasource_id')
    op.create_unique_constraint(None, 'sql_metrics', ['table_id', 'metric_name'])
    op.create_unique_constraint(None, 'table_columns', ['table_id', 'column_name'])
    op.drop_constraint('_customer_location_uc', 'tables', type_='unique')
    op.create_unique_constraint(None, 'tables', ['database_id', 'table_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='unique')
    op.create_unique_constraint('_customer_location_uc', 'tables', ['database_id', 'schema', 'table_name'])
    op.drop_constraint(None, 'table_columns', type_='unique')
    op.drop_constraint(None, 'sql_metrics', type_='unique')
    op.add_column('slices', sa.Column('druid_datasource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('slices', sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('slices_druid_datasource_id_fkey', 'slices', 'datasources', ['druid_datasource_id'], ['id'])
    op.create_foreign_key('slices_table_id_fkey', 'slices', 'tables', ['table_id'], ['id'])
    op.alter_column('dbs', 'allow_csv_upload',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
