"""empty message

Revision ID: d46591f7d3ef
Revises: b3e109bb07cf
Create Date: 2018-12-31 12:48:09.929886

"""

# revision identifiers, used by Alembic.
revision = 'd46591f7d3ef'
down_revision = 'b3e109bb07cf'

from alembic import op
import sqlalchemy as sa
from flask_appbuilder.models.mixins  import FileColumn


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('geojson_file', FileColumn(), nullable=True))

    op.add_column('table_columns', sa.Column('geojson_file', FileColumn(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    op.drop_column('table_columns', 'geojson_file')
    op.drop_column('columns', 'geojson_file')
    # ### end Alembic commands ###
