#!/bin/sh
set -e
exec < /dev/tty
echo "Do you also want to load db_changes? (y/N)"
echo "NOTE: changes that have not been committed and dumped will be lost"
read response
if [ "$response" = "y" ] ||  [ "$response" = "y" ]
then
    docker-compose restart
    docker-compose exec db load
fi

exec <&-
