#!/bin/sh
set -e
exec < /dev/tty
echo "Do you want to include changes to the db? (y/N)"
read response
if [ "$response" = "y" ] ||  [ "$response" = "y" ]
then
    docker-compose exec postgres dump
    git add db/db/superset_data.sql
fi
echo "Proceeding with commit"
exec <&-
